import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  Providers from "./Components/providers";
import TopNav from "./Components/navbar/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TopNav />

          <main className="container mx-auto p-10" >
          {children}
          </main>
        
        </Providers>
        
        </body>
    </html>
  );
}
